[env]
extra_scripts = 

[env:usb]
platform = espressif32
board = esp32dev
framework = arduino
board_build.filesystem = spiffs
monitor_speed = 115200
build_unflags = -std=gnu++11
build_flags =
  -std=gnu++17
  -DDEBUG_LEVEL=2
  -DENABLE_OTA
board_build.partitions = min_spiffs.csv
upload_protocol = esptool
lib_deps =
  bblanchon/ArduinoJson@7.4.1
  https://github.com/CNMAT/OSC.git

[env:dev]
platform = espressif32
board = esp32dev
framework = arduino
board_build.filesystem = spiffs
monitor_speed = 115200
build_unflags = -std=gnu++11
build_flags =
  -std=gnu++17
  -DDEBUG_LEVEL=2
  -DENABLE_OTA
board_build.partitions = min_spiffs.csv
upload_protocol = espota
upload_port = 192.168.4.131
upload_flags =
  --host_port=3232
lib_deps =
  bblanchon/ArduinoJson@7.4.1
  https://github.com/CNMAT/OSC.git

[env:prod]
platform = espressif32
board = esp32dev
framework = arduino
board_build.filesystem = spiffs
monitor_speed = 115200
build_unflags = -std=gnu++11
build_flags =
  -std=gnu++17
  -DDEBUG_LEVEL=0
  -DCONFIG_BT_ENABLED=0
  -DCORE_DEBUG_LEVEL=0
  -DENABLE_OTA
board_build.partitions = min_spiffs.csv
lib_deps =
  bblanchon/ArduinoJson@7.4.1
  https://github.com/CNMAT/OSC.git
